server:
  port: 8081
  servlet:
    context-path: /rocketmq-consumer
spring:
  application:
    name: rocketmq-consumer-demo

rocketmq:
  name-server: 192.168.2.10:9876
  consumer:
    group: rocketmq-consumer-group
